# Generated by Django 3.1.4 on 2020-12-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Toatl_DayTime', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Toatl_WeekTime', models.DecimalField(decimal_places=2, max_digits=5)),
                ('java_DayTime', models.DecimalField(decimal_places=2, max_digits=5)),
                ('java_WeekTime', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rust_DayTime', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rust_WeekTime', models.DecimalField(decimal_places=2, max_digits=5)),
                ('haskell_DayTime', models.DecimalField(decimal_places=2, max_digits=5)),
                ('haskell_WeekTime', models.DecimalField(decimal_places=2, max_digits=5)),
                ('python_DayTime', models.DecimalField(decimal_places=2, max_digits=5)),
                ('python_WeekTime', models.DecimalField(decimal_places=2, max_digits=5)),
                ('kotlin_DayTime', models.DecimalField(decimal_places=2, max_digits=5)),
                ('kotlin_WeekTime', models.DecimalField(decimal_places=2, max_digits=5)),
                ('other_DayTime', models.DecimalField(decimal_places=2, max_digits=5)),
                ('other_WeekTime', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
