# Generated by Django 3.1.4 on 2020-12-13 08:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pluginServer', '0003_remove_time_rustweektime'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
