# Generated by Django 3.1.4 on 2020-12-13 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pluginServer', '0004_time_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='time',
            old_name='cDayTime',
            new_name='c',
        ),
        migrations.RenameField(
            model_name='time',
            old_name='cppDayTime',
            new_name='cpp',
        ),
        migrations.RenameField(
            model_name='time',
            old_name='goDayTime',
            new_name='go',
        ),
        migrations.RenameField(
            model_name='time',
            old_name='haskellDayTime',
            new_name='hs',
        ),
        migrations.RenameField(
            model_name='time',
            old_name='javaDayTime',
            new_name='java',
        ),
        migrations.RenameField(
            model_name='time',
            old_name='jsDayTime',
            new_name='js',
        ),
        migrations.RenameField(
            model_name='time',
            old_name='kotlinDayTime',
            new_name='kt',
        ),
        migrations.RenameField(
            model_name='time',
            old_name='otherDayTime',
            new_name='other',
        ),
        migrations.RenameField(
            model_name='time',
            old_name='rustDayTime',
            new_name='py',
        ),
        migrations.RenameField(
            model_name='time',
            old_name='pythonDayTime',
            new_name='rs',
        ),
        migrations.RenameField(
            model_name='time',
            old_name='totalDayTime',
            new_name='total',
        ),
    ]
